CREATE TABLE `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `remember_token` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `email_alternative` varchar(255) DEFAULT NULL,
  `count_verification` int(11) DEFAULT NULL,
  `status` tinyint(4) NOT NULL DEFAULT 1,
  `phone` varchar(255) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `doc_user_1` varchar(255) DEFAULT NULL,
  `id_contact_epp` varchar(255) DEFAULT NULL,
  `province_id` int(11) DEFAULT NULL,
  `city_id` int(11) DEFAULT NULL,
  `postal_code` char(6) DEFAULT NULL,
  `name_organization` text DEFAULT NULL,
  `address` text DEFAULT NULL,
  `fax` varchar(255) DEFAULT NULL,
  `is_migrasi` tinyint(4) DEFAULT NULL,
  `send_email` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=123994 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;